server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php index.html;

    # Health endpoint simple
    location /health { return 200 "OK"; }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Archivos estáticos (cacheable)
    location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|webp|ico|woff2?)$ {
        expires 7d;
        access_log off;
        try_files $uri =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_pass app:9000;
        fastcgi_read_timeout 300s;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    client_max_body_size 20m;
}